/* Generated by convert_backgrounds.py. Do not edit. */
#ifndef COUP_BG_INDEX_H
#define COUP_BG_INDEX_H

/* Scenes are streamed from the disc, not linked in. Each
   file is a 512-byte big-endian RGB555 palette followed by
   224 rows of 320 8bpp pixels. */

#define COUP_BG_VISIBLE_W 320
#define COUP_BG_VISIBLE_H 224
#define COUP_BG_W 512
#define COUP_BG_H 256
#define COUP_BG_PAL_BYTES 512
#define COUP_BG_PIX_BYTES 71680
#define COUP_BG_FILE_BYTES 72192
#define COUP_BG_SCENE_COUNT 7

enum {
    COUP_BG_SCENE_GAME = 0,
    COUP_BG_SCENE_TITLE = 1,
    COUP_BG_SCENE_RULES = 2,
    COUP_BG_SCENE_LOBBY = 3,
    COUP_BG_SCENE_CONNECTING = 4,
    COUP_BG_SCENE_VICTORY = 5,
    COUP_BG_SCENE_DEFEAT = 6,
};

/* Source artwork, for the fidelity gate. Do not edit.
   COUP_BG_SOURCE game = Official Art/coup_saturn_complete_asset_pack/coup_saturn_complete_asset_pack/saturn_ready/backgrounds/B2_game_table.png
   COUP_BG_SOURCE title = Official Art/coup_saturn_complete_asset_pack/coup_saturn_complete_asset_pack/saturn_ready/backgrounds/B1_title.png
   COUP_BG_SOURCE rules = Official Art/rulesoverlay.png
   COUP_BG_SOURCE lobby = Official Art/coup_saturn_complete_asset_pack/coup_saturn_complete_asset_pack/saturn_ready/backgrounds/B3_lobby.png
   COUP_BG_SOURCE connecting = Official Art/coup_saturn_complete_asset_pack/coup_saturn_complete_asset_pack/saturn_ready/backgrounds/B4_connecting.png
   COUP_BG_SOURCE victory = Official Art/coup_saturn_complete_asset_pack/coup_saturn_complete_asset_pack/saturn_ready/backgrounds/B5_victory.png
   COUP_BG_SOURCE defeat = Official Art/coup_saturn_complete_asset_pack/coup_saturn_complete_asset_pack/saturn_ready/backgrounds/B6_defeat.png
*/

static const char* const coup_bg_files[COUP_BG_SCENE_COUNT] = {
    "BGGAME.BIN",
    "BGTITLE.BIN",
    "BGRULES.BIN",
    "BGLOBBY.BIN",
    "BGCONNEC.BIN",
    "BGVICTOR.BIN",
    "BGDEFEAT.BIN",
};

#endif /* COUP_BG_INDEX_H */
