/* Generated by convert_portraits.py. Do not edit. */
#ifndef COUP_ANIM_SPRITES_H
#define COUP_ANIM_SPRITES_H

#include <stdint.h>

#define COUP_ANIM_W           64
#define COUP_ANIM_H           96
#define COUP_ANIM_FRAME_SIZE  3072
#define COUP_ANIM_FRAMES      8
#define COUP_ANIM_CHARS       5
#define COUP_ANIM_TOTAL_FRAMES (8 * 5)
#define COUP_ANIM_TOTAL_SIZE  (8 * 5 * 3072)

#define COUP_ANIM_DUKE  0
#define COUP_ANIM_ASSASSIN  1
#define COUP_ANIM_CAPTAIN  2
#define COUP_ANIM_AMBASSADOR  3
#define COUP_ANIM_CONTESSA  4

static const uint16_t coup_anim_pal_duke[16] = {
    0x0000, 0x3699, 0x21D3, 0x1D6F,
    0x194D, 0x190B, 0x1CEB, 0x18C9,
    0x1C89, 0x1487, 0x1086, 0x1065,
    0x1064, 0x0C43, 0x0421, 0x0401,
};

static const uint16_t coup_anim_pal_assassin[16] = {
    0x0000, 0x5AF9, 0x4A76, 0x4210,
    0x31AD, 0x316A, 0x3148, 0x2927,
    0x1CE6, 0x18A4, 0x1062, 0x0841,
    0x0821, 0x0421, 0x0000, 0x0000,
};

static const uint16_t coup_anim_pal_captain[16] = {
    0x0000, 0x52B6, 0x39AB, 0x3966,
    0x3945, 0x2507, 0x3125, 0x2904,
    0x28E4, 0x18A4, 0x1CA3, 0x1C80,
    0x1860, 0x1040, 0x0C20, 0x0420,
};

static const uint16_t coup_anim_pal_ambassador[16] = {
    0x0000, 0x2676, 0x1E14, 0x19D1,
    0x19D1, 0x0997, 0x198F, 0x156D,
    0x112B, 0x08EF, 0x08EC, 0x0D09,
    0x08C8, 0x08C7, 0x08A6, 0x0464,
};

static const uint16_t coup_anim_pal_contessa[16] = {
    0x0000, 0x3E9C, 0x2E3B, 0x21B7,
    0x0D11, 0x088F, 0x086D, 0x086C,
    0x046B, 0x042D, 0x002A, 0x0009,
    0x0007, 0x0006, 0x0004, 0x0003,
};

static const uint16_t* const coup_anim_palettes[5] = {
    coup_anim_pal_duke,
    coup_anim_pal_assassin,
    coup_anim_pal_captain,
    coup_anim_pal_ambassador,
    coup_anim_pal_contessa,
};

#endif /* COUP_ANIM_SPRITES_H */
