/**
 * coup_sprites.h - Auto-generated sprite metadata for Coup
 *
 * Generated by convert_assets.py. Do not edit manually.
 *
 * Each sprite is stored as a .bin file on the CD filesystem.
 * Palettes are embedded here for direct CRAM upload.
 */

#ifndef COUP_SPRITES_H
#define COUP_SPRITES_H

#include <stdint.h>

/*============================================================================
 * Sprite Dimensions
 *============================================================================*/

#define COUP_SPR_DUKE_W   64
#define COUP_SPR_DUKE_H   96
#define COUP_SPR_DUKE_SIZE 3072  /* bytes (4bpp) */

#define COUP_SPR_ASSASSIN_W   64
#define COUP_SPR_ASSASSIN_H   96
#define COUP_SPR_ASSASSIN_SIZE 3072  /* bytes (4bpp) */

#define COUP_SPR_CAPTAIN_W   64
#define COUP_SPR_CAPTAIN_H   96
#define COUP_SPR_CAPTAIN_SIZE 3072  /* bytes (4bpp) */

#define COUP_SPR_AMBASSADOR_W   64
#define COUP_SPR_AMBASSADOR_H   96
#define COUP_SPR_AMBASSADOR_SIZE 3072  /* bytes (4bpp) */

#define COUP_SPR_CONTESSA_W   64
#define COUP_SPR_CONTESSA_H   96
#define COUP_SPR_CONTESSA_SIZE 3072  /* bytes (4bpp) */

#define COUP_SPR_CARD_BACK_W   48
#define COUP_SPR_CARD_BACK_H   72
#define COUP_SPR_CARD_BACK_SIZE 1728  /* bytes (4bpp) */

#define COUP_SPR_TITLE_W   256
#define COUP_SPR_TITLE_H   64
#define COUP_SPR_TITLE_SIZE 8192  /* bytes (4bpp) */

#define COUP_SPR_COIN_W   16
#define COUP_SPR_COIN_H   16
#define COUP_SPR_COIN_SIZE 128  /* bytes (4bpp) */

#define COUP_SPR_BG_TILE_W   32
#define COUP_SPR_BG_TILE_H   32
#define COUP_SPR_BG_TILE_SIZE 512  /* bytes (4bpp) */

#define COUP_SPR_TOTAL_SIZE 25920  /* total bytes for all sprites */

/*============================================================================
 * Sprite Indices
 *============================================================================*/

enum {
    COUP_SPR_DUKE = 0,
    COUP_SPR_ASSASSIN = 1,
    COUP_SPR_CAPTAIN = 2,
    COUP_SPR_AMBASSADOR = 3,
    COUP_SPR_CONTESSA = 4,
    COUP_SPR_CARD_BACK = 5,
    COUP_SPR_TITLE = 6,
    COUP_SPR_COIN = 7,
    COUP_SPR_BG_TILE = 8,
    COUP_SPR_COUNT = 9
};

/*============================================================================
 * CD Filenames (for loading)
 *============================================================================*/

static const char* const coup_spr_filenames[COUP_SPR_COUNT] = {
    "DUKE.BIN",
    "ASSASSIN.BIN",
    "CAPTAIN.BIN",
    "AMBASSAD.BIN",
    "CONTESSA.BIN",
    "CARD_BAC.BIN",
    "TITLE.BIN",
    "COIN.BIN",
    "BG_TILE.BIN",
};

/*============================================================================
 * Palette Data (Saturn RGB555, 16 colors per sprite)
 *============================================================================*/

static const uint16_t coup_pal_duke[16] = {
    0x0000, 0x1E7B, 0x0D96, 0x0913,
    0x08ED, 0x106F, 0x086B, 0x0468,
    0x0446, 0x0C2A, 0x0827, 0x0825,
    0x0825, 0x0823, 0x0422, 0x0402,
};

static const uint16_t coup_pal_assassin[16] = {
    0x0000, 0x2617, 0x0CCA, 0x044B,
    0x0444, 0x0429, 0x0426, 0x0424,
    0x0423, 0x0025, 0x0023, 0x0023,
    0x0003, 0x0022, 0x0022, 0x0002,
};

static const uint16_t coup_pal_captain[16] = {
    0x0000, 0x2ABC, 0x1618, 0x0995,
    0x194F, 0x04EE, 0x0CCA, 0x1CC6,
    0x1485, 0x0466, 0x0844, 0x1843,
    0x0422, 0x1821, 0x0422, 0x0821,
};

static const uint16_t coup_pal_ambassador[16] = {
    0x0000, 0x1EBC, 0x1239, 0x09B6,
    0x096D, 0x050F, 0x04AC, 0x08E4,
    0x04A5, 0x0468, 0x0466, 0x0444,
    0x0443, 0x0461, 0x0441, 0x0421,
};

static const uint16_t coup_pal_contessa[16] = {
    0x0000, 0x1EDE, 0x165C, 0x0DF9,
    0x0DB6, 0x0953, 0x0511, 0x04ED,
    0x04AB, 0x008A, 0x0068, 0x0467,
    0x0046, 0x0044, 0x0023, 0x0002,
};

static const uint16_t coup_pal_card_back[16] = {
    0x0000, 0x2637, 0x15B2, 0x0D71,
    0x114F, 0x0D2D, 0x0CEC, 0x0CCA,
    0x10C8, 0x0C87, 0x1085, 0x1863,
    0x1063, 0x0C21, 0x0401, 0x0400,
};

static const uint16_t coup_pal_title[16] = {
    0x0000, 0x3BDF, 0x1F5E, 0x12DC,
    0x0E38, 0x05B5, 0x0133, 0x054F,
    0x010E, 0x00CE, 0x00CA, 0x0088,
    0x0045, 0x0043, 0x0023, 0x0002,
};

static const uint16_t coup_pal_coin[16] = {
    0x0000, 0x2AFC, 0x167B, 0x0E5B,
    0x1259, 0x0E3A, 0x0E38, 0x0E17,
    0x11F6, 0x09B5, 0x0993, 0x0D4E,
    0x090B, 0x04A9, 0x0065, 0x0022,
};

static const uint16_t coup_pal_bg_tile[16] = {
    0x0000, 0x1884, 0x1863, 0x1463,
    0x1463, 0x1462, 0x1062, 0x1042,
    0x1042, 0x1042, 0x1042, 0x1042,
    0x1042, 0x0C41, 0x0C41, 0x0C21,
};

static const uint16_t* const coup_palettes[COUP_SPR_COUNT] = {
    coup_pal_duke,
    coup_pal_assassin,
    coup_pal_captain,
    coup_pal_ambassador,
    coup_pal_contessa,
    coup_pal_card_back,
    coup_pal_title,
    coup_pal_coin,
    coup_pal_bg_tile,
};

/*============================================================================
 * Sprite Info Table
 *============================================================================*/

typedef struct {
    uint16_t w;
    uint16_t h;
    uint16_t data_size;
} coup_spr_info_t;

static const coup_spr_info_t coup_spr_info[COUP_SPR_COUNT] = {
    { 64, 96, 3072 },  /* duke */
    { 64, 96, 3072 },  /* assassin */
    { 64, 96, 3072 },  /* captain */
    { 64, 96, 3072 },  /* ambassador */
    { 64, 96, 3072 },  /* contessa */
    { 48, 72, 1728 },  /* card_back */
    { 256, 64, 8192 },  /* title */
    { 16, 16, 128 },  /* coin */
    { 32, 32, 512 },  /* bg_tile */
};

#endif /* COUP_SPRITES_H */
