/* Generated by convert_portraits.py. Do not edit. */
#ifndef COUP_ANIM_SPRITES_H
#define COUP_ANIM_SPRITES_H

#include <stdint.h>

#define COUP_ANIM_W           64
#define COUP_ANIM_H           96
#define COUP_ANIM_FRAME_SIZE  3072
#define COUP_ANIM_FRAMES      8
#define COUP_ANIM_CHARS       5
#define COUP_ANIM_TOTAL_FRAMES (8 * 5)
#define COUP_ANIM_TOTAL_SIZE  (8 * 5 * 3072)

#define COUP_ANIM_DUKE  0
#define COUP_ANIM_ASSASSIN  1
#define COUP_ANIM_CAPTAIN  2
#define COUP_ANIM_AMBASSADOR  3
#define COUP_ANIM_CONTESSA  4

static const uint16_t coup_anim_pal_duke[16] = {
    0x0000, 0x3EFD, 0x3298, 0x2A37,
    0x2A14, 0x25F3, 0x1DB1, 0x218F,
    0x1D6E, 0x192C, 0x20EC, 0x14E9,
    0x14A8, 0x1887, 0x1465, 0x0822,
};

static const uint16_t coup_anim_pal_assassin[16] = {
    0x0000, 0x5F3C, 0x56D8, 0x4A97,
    0x5273, 0x3A33, 0x4630, 0x41EE,
    0x35AD, 0x296D, 0x2D6A, 0x2948,
    0x1CE7, 0x18C4, 0x0C63, 0x0400,
};

static const uint16_t coup_anim_pal_captain[16] = {
    0x0000, 0x633A, 0x5292, 0x420F,
    0x49C9, 0x35AB, 0x3DA9, 0x3967,
    0x2D47, 0x2507, 0x2D25, 0x24E3,
    0x1CA1, 0x1C80, 0x1060, 0x0400,
};

static const uint16_t coup_anim_pal_ambassador[16] = {
    0x0000, 0x2AB6, 0x2E75, 0x2635,
    0x2633, 0x09DA, 0x1DF2, 0x1DD0,
    0x0D53, 0x194D, 0x08EF, 0x0CCB,
    0x1108, 0x0CC7, 0x0886, 0x0444,
};

static const uint16_t coup_anim_pal_contessa[16] = {
    0x0000, 0x4EFD, 0x3ABB, 0x2E7A,
    0x3258, 0x2218, 0x15B7, 0x25D4,
    0x1593, 0x1152, 0x110E, 0x0894,
    0x086D, 0x0889, 0x042A, 0x0007,
};

static const uint16_t* const coup_anim_palettes[5] = {
    coup_anim_pal_duke,
    coup_anim_pal_assassin,
    coup_anim_pal_captain,
    coup_anim_pal_ambassador,
    coup_anim_pal_contessa,
};

#endif /* COUP_ANIM_SPRITES_H */
