/**
 * coup_anim_sprites.h - Animated sprite metadata for Coup
 *
 * Generated by convert_animated.py. Do not edit manually.
 *
 * Each character has multiple animation frames stored as 4bpp
 * VDP1 textures sharing a single 16-color palette.
 */

#ifndef COUP_ANIM_SPRITES_H
#define COUP_ANIM_SPRITES_H

#include <stdint.h>

/*============================================================================
 * Animation Constants
 *============================================================================*/

#define COUP_ANIM_W           32
#define COUP_ANIM_H           48
#define COUP_ANIM_FRAME_SIZE  768  /* bytes per frame (4bpp) */
#define COUP_ANIM_FRAMES      24  /* frames per character */
#define COUP_ANIM_CHARS       5   /* number of animated characters */
#define COUP_ANIM_TOTAL_FRAMES (24 * 5)  /* total frames */
#define COUP_ANIM_TOTAL_SIZE  (24 * 5 * 768)  /* total bytes */

/*============================================================================
 * Character Indices (same order as COUP_CHAR_* in coup.h)
 *============================================================================*/

#define COUP_ANIM_DUKE  0
#define COUP_ANIM_ASSASSIN  1
#define COUP_ANIM_CAPTAIN  2
#define COUP_ANIM_AMBASSADOR  3
#define COUP_ANIM_CONTESSA  4

/*============================================================================
 * Palette Data (Saturn RGB555, 16 colors per character)
 *============================================================================*/

static const uint16_t coup_anim_pal_duke[16] = {
    0x0000, 0x1A39, 0x0D73, 0x08F2,
    0x08EC, 0x106E, 0x086A, 0x0467,
    0x0446, 0x0C29, 0x0826, 0x0424,
    0x0804, 0x0423, 0x0402, 0x0402,
};

static const uint16_t coup_anim_pal_assassin[16] = {
    0x0000, 0x2DF4, 0x14EA, 0x0868,
    0x0C64, 0x0429, 0x0426, 0x0423,
    0x0821, 0x0026, 0x0004, 0x0003,
    0x0003, 0x0002, 0x0001, 0x0002,
};

static const uint16_t coup_anim_pal_captain[16] = {
    0x0000, 0x2ABB, 0x15D5, 0x0932,
    0x212B, 0x08CC, 0x10C8, 0x2CA5,
    0x1086, 0x0865, 0x1863, 0x0843,
    0x0423, 0x2041, 0x0C21, 0x0801,
};

static const uint16_t coup_anim_pal_ambassador[16] = {
    0x0000, 0x22DD, 0x1239, 0x0DB6,
    0x0D6C, 0x0910, 0x04CC, 0x0905,
    0x04A5, 0x0468, 0x0466, 0x0444,
    0x0423, 0x0461, 0x0441, 0x0021,
};

static const uint16_t coup_anim_pal_contessa[16] = {
    0x0000, 0x26DE, 0x1619, 0x0DB6,
    0x1172, 0x0931, 0x04EF, 0x0CEC,
    0x08AB, 0x048A, 0x0468, 0x0466,
    0x0045, 0x0424, 0x0023, 0x0002,
};

static const uint16_t* const coup_anim_palettes[5] = {
    coup_anim_pal_duke,
    coup_anim_pal_assassin,
    coup_anim_pal_captain,
    coup_anim_pal_ambassador,
    coup_anim_pal_contessa,
};

#endif /* COUP_ANIM_SPRITES_H */
