#!/usr/bin/env python3
"""
convert_backgrounds.py - Convert a Coup scene PNG to a VDP2 NBG1 bitmap.

Output format (ST-058-R2 section 4.9, bitmap-mode scroll screens):
  - 512x256 bitmap, one byte per pixel (256-colour mode)
  - the visible 320x224 window occupies the top-left corner
  - palette index 0 is TRANSPARENT for a scroll screen, so it is reserved:
    image colours occupy indices 1..255
  - palette entries are Saturn RGB555, 0BBBBBGGGGGRRRRR, bit 15 clear

The bitmap is exactly 0x20000 bytes, which is one whole VDP2 VRAM bank. It is
uploaded to bank A0 at 0x25E00000 (bitmap base must be 0x20000-aligned), and
NOT to bank B1, where the text layer's character data lives - SGL's auto
arbiter non-deterministically drops a standalone NBG whose data sits in B1
(sega-saturn-developer gotcha #7, MEASURED).

Usage:
  python3 convert_backgrounds.py gamescreen.png --name game \
      --output ../saturn/coup_bg_data.h [--preview out.png]
"""

import argparse
import os
import sys

from PIL import Image

BITMAP_W = 512
BITMAP_H = 256
VISIBLE_W = 320
VISIBLE_H = 224
RESERVED_INDICES = 1                      # index 0 = transparent
MAX_COLORS = 256 - RESERVED_INDICES       # 255 usable colours


def to_rgb555(r, g, b):
    """Pack 8-bit RGB into Saturn RGB555 (bit 15 clear)."""
    return ((b >> 3) << 10) | ((g >> 3) << 5) | (r >> 3)


def convert(src_path):
    """Return (bitmap_bytes, palette_list, preview_image)."""
    img = Image.open(src_path).convert("RGB")
    img = img.resize((VISIBLE_W, VISIBLE_H), Image.LANCZOS)

    quant = img.quantize(colors=MAX_COLORS, method=Image.MEDIANCUT)
    src_palette = quant.getpalette()[: MAX_COLORS * 3]
    indices = quant.tobytes()   # P-mode: raw palette indices, one byte each

    # Shift every index up by RESERVED_INDICES so index 0 stays transparent.
    palette = [0x0000] * 256
    for i in range(MAX_COLORS):
        r, g, b = src_palette[i * 3: i * 3 + 3]
        palette[i + RESERVED_INDICES] = to_rgb555(r, g, b)

    bitmap = bytearray(BITMAP_W * BITMAP_H)   # zero-filled = transparent
    for y in range(VISIBLE_H):
        row = y * BITMAP_W
        src_row = y * VISIBLE_W
        for x in range(VISIBLE_W):
            bitmap[row + x] = indices[src_row + x] + RESERVED_INDICES

    return bytes(bitmap), palette, quant.convert("RGB")


def verify(bitmap, palette):
    """Assert every hardware invariant before emitting anything."""
    assert len(bitmap) == BITMAP_W * BITMAP_H, (
        f"bitmap must be exactly {BITMAP_W * BITMAP_H} bytes (one VDP2 bank), "
        f"got {len(bitmap)}")

    assert palette[0] == 0x0000, (
        "palette index 0 must stay reserved: VDP2 treats colour 0 in a scroll "
        "screen as transparent")

    bad = [c for c in palette if c > 0x7FFF]
    assert not bad, f"RGB555 bit 15 must be clear, found {len(bad)} entries above 0x7FFF"

    for y in range(VISIBLE_H):
        row = bitmap[y * BITMAP_W: y * BITMAP_W + VISIBLE_W]
        assert 0 not in row, (
            f"visible row {y} uses the transparent index - the background "
            "would show holes")

    used = set(bitmap[y * BITMAP_W: y * BITMAP_W + VISIBLE_W][x]
               for y in range(VISIBLE_H) for x in range(VISIBLE_W))
    assert max(used) <= 255, "index out of range"
    return {"colours_used": len(used)}


def emit_header(scenes, out_path):
    """Emit one header holding every scene, plus a lookup table.

    `scenes` is a list of (name, bitmap, palette) in enum order.
    """
    guard = "COUP_BG_DATA_H"
    with open(out_path, "w") as f:
        f.write("/* Generated by convert_backgrounds.py. Do not edit. */\n")
        f.write(f"#ifndef {guard}\n#define {guard}\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define COUP_BG_W {BITMAP_W}\n")
        f.write(f"#define COUP_BG_H {BITMAP_H}\n")
        f.write(f"#define COUP_BG_VISIBLE_W {VISIBLE_W}\n")
        f.write(f"#define COUP_BG_VISIBLE_H {VISIBLE_H}\n")
        f.write(f"#define COUP_BG_SIZE {BITMAP_W * BITMAP_H}\n")
        f.write(f"#define COUP_BG_SCENE_COUNT {len(scenes)}\n\n")

        f.write("enum {\n")
        for i, (name, _, _) in enumerate(scenes):
            f.write(f"    COUP_BG_SCENE_{name.upper()} = {i},\n")
        f.write("};\n\n")

        for name, bitmap, palette in scenes:
            f.write(f"/* --- {name} --- */\n")
            f.write("/* Saturn RGB555. Index 0 is transparent and unused. */\n")
            f.write(f"static const uint16_t coup_bg_pal_{name}[256] = {{\n")
            for i in range(0, 256, 8):
                row = ", ".join(f"0x{c:04X}" for c in palette[i:i + 8])
                f.write(f"    {row},\n")
            f.write("};\n\n")

            f.write(f"static const uint8_t coup_bg_tbl_{name}[{len(bitmap)}] = {{\n")
            for i in range(0, len(bitmap), 16):
                row = ", ".join(f"0x{b:02X}" for b in bitmap[i:i + 16])
                f.write(f"    {row},\n")
            f.write("};\n\n")

        f.write("static const uint8_t* const coup_bg_tables[COUP_BG_SCENE_COUNT] = {\n")
        for name, _, _ in scenes:
            f.write(f"    coup_bg_tbl_{name},\n")
        f.write("};\n\n")

        f.write("static const uint16_t* const coup_bg_palettes[COUP_BG_SCENE_COUNT] = {\n")
        for name, _, _ in scenes:
            f.write(f"    coup_bg_pal_{name},\n")
        f.write("};\n\n")

        f.write(f"#endif /* {guard} */\n")


def main():
    ap = argparse.ArgumentParser(
        description="Convert one or more scene PNGs into a VDP2 bitmap header.")
    ap.add_argument("--scene", action="append", required=True, metavar="NAME=PATH",
                    help="scene to include, in enum order; repeatable")
    ap.add_argument("--output", required=True)
    ap.add_argument("--preview-dir", help="write quantized previews here")
    args = ap.parse_args()

    scenes = []
    for spec in args.scene:
        if "=" not in spec:
            raise SystemExit(f"--scene expects NAME=PATH, got {spec!r}")
        name, path = spec.split("=", 1)

        bitmap, palette, preview = convert(path)
        stats = verify(bitmap, palette)
        scenes.append((name, bitmap, palette))

        if args.preview_dir:
            os.makedirs(args.preview_dir, exist_ok=True)
            preview.save(os.path.join(args.preview_dir, f"bg-{name}.png"))

        print(f"  {name:<10} {os.path.basename(path):<24} "
              f"{stats['colours_used']:>3} colours")

    emit_header(scenes, args.output)

    total = len(scenes) * BITMAP_W * BITMAP_H
    print(f"-> {args.output}")
    print(f"   {len(scenes)} scene(s), {BITMAP_W}x{BITMAP_H} 8bpp, "
          f"{total:,} bytes of bitmap data")
    print(f"   header {os.path.getsize(args.output):,} bytes of source")
    return 0


if __name__ == "__main__":
    sys.exit(main())
