/**
 * coup_sfx_ids.h - Sound effect ids and budget figures.
 *
 * Auto-generated by examples/coup/assets/convert_sfx.py. Do not edit.
 *
 * Split out of coup_sfx_data.h on purpose: coup.h includes THIS
 * header so every call site can name an effect, while the PCM
 * arrays stay in coup_sfx_data.h. `static const` arrays in a header
 * are duplicated once per translation unit, so putting the waveform
 * data here would put a copy of it in every object file.
 */

#ifndef COUP_SFX_IDS_H
#define COUP_SFX_IDS_H

#define COUP_SFX_COUNT 21

/* Bytes the generated set occupies in Sound RAM, and the space
 * available to it. coup_audio.c static-asserts the first against
 * the second: sfx_upload_to_sound_ram() has no run-time bound and
 * would write straight over the sound driver's memory. */
#define COUP_SFX_TOTAL_BYTES  67400
#define COUP_SFX_BUDGET_BYTES 81920

#define COUP_SFX_RATE_HIGH 11025
#define COUP_SFX_RATE_LOW  5512

#define COUP_SFX_UI_MOVE        0   /* short dry tick, no tail - d-pad movement */
#define COUP_SFX_UI_CONFIRM     1   /* rising two-tone, affirmative - A / Start */
#define COUP_SFX_UI_CANCEL      2   /* falling, the confirm inverted - B / back */
#define COUP_SFX_UI_CHALLENGE   3   /* sharper and more urgent than confirm - C shortcut */
#define COUP_SFX_CARD_DEAL      4   /* one paper slide - a card dealt */
#define COUP_SFX_DECK_PLACE     5   /* heavier, a stack landing - the court deck */
#define COUP_SFX_CARD_REVEAL    6   /* a card turned face up, with weight */
#define COUP_SFX_CARD_SHUFFLE   7   /* cards moving, riffled - Ambassador exchange */
#define COUP_SFX_COIN_GAIN      8   /* bright metal, upward - income, foreign aid, tax */
#define COUP_SFX_COIN_SPEND     9   /* duller, downward - paying out */
#define COUP_SFX_COUP_STRIKE    10  /* heavy and final - the most expensive act in the game */
#define COUP_SFX_TURN_START     11  /* short low chime, expectant - whose turn it is */
#define COUP_SFX_INFLUENCE_LOST 12  /* descending, damaged - an influence is gone */
#define COUP_SFX_EXILED         13  /* terminal, lower and longer than losing influence */
#define COUP_SFX_CHALLENGE      14  /* sharp, confrontational, rising */
#define COUP_SFX_COUNTER        15  /* firm, closing - a door shutting */
#define COUP_SFX_ACT_SUCCESS    16  /* resolved, upward */
#define COUP_SFX_ACT_FAIL       17  /* deflating, downward */
#define COUP_SFX_ASSASSINATE    18  /* a blade - quiet, then sharp */
#define COUP_SFX_STEAL          19  /* a snatch - coin plus a quick drag */
#define COUP_SFX_VICTORY        20  /* a three-note figure - the game is won */

/* Compatibility aliases for the pre-expansion 8-effect names.
 * Kept so an old call site cannot silently pick up a different
 * sound; new code should use the names above. */
#define COUP_SFX_CONFIRM     COUP_SFX_UI_CONFIRM
#define COUP_SFX_CANCEL      COUP_SFX_UI_CANCEL
#define COUP_SFX_COINS       COUP_SFX_COIN_GAIN
#define COUP_SFX_ELIMINATED  COUP_SFX_EXILED

#endif /* COUP_SFX_IDS_H */
