/**
 * saturn_font_alagard_16x16.h - alagard_16x16 font data for Saturn VDP1
 *
 * Auto-generated by ttf_to_c.py from alagard_16x16 TTF
 * License: CC-BY 3.0
 * Author: Hewett Tsoi / PIX3M
 */

#ifndef SATURN_FONT_ALAGARD_16X16_H
#define SATURN_FONT_ALAGARD_16X16_H

#include "../saturn_font.h"

void saturn_font_alagard_16x16_desc(saturn_font_desc_t* desc);

#endif /* SATURN_FONT_ALAGARD_16X16_H */
