/**
 * saturn_font_spleen_5x8.h - spleen_5x8 font data for Saturn VDP1
 *
 * Auto-generated by bdf_to_c.py
 * License: BSD-2-Clause
 * Author: Frederic Cambus
 */

#ifndef SATURN_FONT_SPLEEN_5X8_H
#define SATURN_FONT_SPLEEN_5X8_H

#include "../saturn_font.h"

void saturn_font_spleen_5x8_desc(saturn_font_desc_t* desc);

#endif /* SATURN_FONT_SPLEEN_5X8_H */
