/**
 * saturn_font_buch_8x12.h - buch_8x12 font data for Saturn VDP1
 *
 * Auto-generated by buch_extract.py from Three Little Bitmap Fonts
 * License: CC0
 * Author: buch
 */

#ifndef SATURN_FONT_BUCH_8X12_H
#define SATURN_FONT_BUCH_8X12_H

#include "../saturn_font.h"

void saturn_font_buch_8x12_desc(saturn_font_desc_t* desc);

#endif /* SATURN_FONT_BUCH_8X12_H */
