/**
 * saturn_font_bubblemad_8x8.h - bubblemad_8x8 font data for Saturn VDP1
 *
 * Auto-generated by png_to_c.py
 * License: CC-BY 4.0
 * Author: ZiNGOT / Zingot Games
 */

#ifndef SATURN_FONT_BUBBLEMAD_8X8_H
#define SATURN_FONT_BUBBLEMAD_8X8_H

#include "../saturn_font.h"

void saturn_font_bubblemad_8x8_desc(saturn_font_desc_t* desc);

#endif /* SATURN_FONT_BUBBLEMAD_8X8_H */
