/**
 * saturn_font_kromasky_16x16.h - kromasky_16x16 font data for Saturn VDP1
 *
 * Auto-generated by png_to_c.py
 * License: CC-BY 4.0
 * Author: ZiNGOT / Zingot Games
 */

#ifndef SATURN_FONT_KROMASKY_16X16_H
#define SATURN_FONT_KROMASKY_16X16_H

#include "../saturn_font.h"

void saturn_font_kromasky_16x16_desc(saturn_font_desc_t* desc);

#endif /* SATURN_FONT_KROMASKY_16X16_H */
