/**
 * saturn_font_buch_16x24.h - buch_16x24 font data for Saturn VDP1
 *
 * Auto-generated by buch_extract.py from Three Little Bitmap Fonts
 * License: CC0
 * Author: buch
 */

#ifndef SATURN_FONT_BUCH_16X24_H
#define SATURN_FONT_BUCH_16X24_H

#include "../saturn_font.h"

void saturn_font_buch_16x24_desc(saturn_font_desc_t* desc);

#endif /* SATURN_FONT_BUCH_16X24_H */
