/**
 * saturn_font_spleen_8x16.h - spleen_8x16 font data for Saturn VDP1
 *
 * Auto-generated by bdf_to_c.py
 * License: BSD-2-Clause
 * Author: Frederic Cambus
 */

#ifndef SATURN_FONT_SPLEEN_8X16_H
#define SATURN_FONT_SPLEEN_8X16_H

#include "../saturn_font.h"

void saturn_font_spleen_8x16_desc(saturn_font_desc_t* desc);

#endif /* SATURN_FONT_SPLEEN_8X16_H */
