/**
 * saturn_font_alagard_8x8.h - alagard_8x8 font data for Saturn VDP1
 *
 * Auto-generated by ttf_to_c.py from alagard_8x8 TTF
 * License: CC-BY 3.0
 * Author: Hewett Tsoi / PIX3M
 */

#ifndef SATURN_FONT_ALAGARD_8X8_H
#define SATURN_FONT_ALAGARD_8X8_H

#include "../saturn_font.h"

void saturn_font_alagard_8x8_desc(saturn_font_desc_t* desc);

#endif /* SATURN_FONT_ALAGARD_8X8_H */
