/**
 * saturn_font_buch_4x6.h - buch_4x6 font data for Saturn VDP1
 *
 * Auto-generated by buch_extract.py from Three Little Bitmap Fonts
 * License: CC0
 * Author: buch
 */

#ifndef SATURN_FONT_BUCH_4X6_H
#define SATURN_FONT_BUCH_4X6_H

#include "../saturn_font.h"

void saturn_font_buch_4x6_desc(saturn_font_desc_t* desc);

#endif /* SATURN_FONT_BUCH_4X6_H */
